### ISSUE TITLE
_putDoubleQuotes issues

### ISSUE THREAD

**Issue by poioit** [bnjjj/node-request-digest#3]
when I use the for gerrit login, it encounters a permission denied.
I check that in the "_putDoubleQuotes"
**return (_.includes(excludeList, i) ? true : false);**
if the parameters in the exclude list, we will use the double quotes.
I think it should return false when it in the exclude list.
SO I change this to 
**return (_.includes(excludeList, i) ? true : false);**
it works.
How do you think about this?

**Comment by bnjjj** [comment]
I'm not sure to good understand but if I look into my code here : https://github.com/bnjjj/node-request-digest/blob/master/request-digest.es6.js#L155

I see "return (_.includes(excludeList, i) ? true : false);" and you suggest me to use "return (_.includes(excludeList, i) ? true : false);" I don't see the difference.

Could you explain me in more details please. Maybe you've made a mistake in your issue explanation ?

**Comment by poioit** [comment]
sorry, typo
SO I change this to 
**return (_.includes(excludeList, i) ? false : true);**
it means if this parameter is in the excludelist, it should not use Quotes.
Those parameters not in the excludelist, it should use the Quotes.

**Comment by bnjjj** [comment]
Right ! I'll look at this issue this weekend !

**Comment by bnjjj** [comment]
Alright I have tested your improvements and include it ! https://github.com/bnjjj/node-request-digest/blob/master/request-digest.es6.js#L175

I have added a promise support like mentioned here https://github.com/bnjjj/node-request-digest#usage-promise-only--100

And then add a better error support too : https://github.com/bnjjj/node-request-digest#return-object

In order to get this improvements you have to re-install manually the package via npm i because I have upgraded the version with a major (1.0.0)

Let me know if it's good for you and if you like this npm you can star this one on github and npmjs.com ! It's very encouraging !
